# Generated by Django 5.2.8 on 2025-12-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0004_alter_freelancer_options_alter_profession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mygigs.review'),
        ),
    ]
